[theme]
primaryColor = "#f97316"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
showSidebarNavigation = false
