[theme]
primaryColor = "#f97316"          # Naranja Nutrisco
backgroundColor = "#0f172a"       # Fondo oscuro
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false