# .streamlit/secrets.toml
OPENAI_API_KEY = "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"

# Correo de Bel√©n
BELEN_EMAIL = "belen.bastias@nutrisco.com"